# -*- coding: utf-8 -*-
"""Automate_m. Haidar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JCJldkCxKn-oF_2bbmpTwBbuTAh8CiP9
"""

import pandas as pd
import os

def load_data():
  # Load Data
    input_path = '/content/drive/MyDrive/Tugas Pijak/SMSL_M. Haidar/house_price_raw.csv'

    if not os.path.exists(input_path):
        print(f"Error: File {input_path} tidak ditemukan!")
        return

    df = pd.read_csv(input_path)
    print(f"Memproses data... Baris awal: {df.shape[0]}")

def run_preprocessing(df):
    # Hapus kolom non-numerik
    cols_to_drop = ['date', 'street', 'city', 'statezip', 'country']
    df_clean = df.drop(columns=[c for c in cols_to_drop if c in df.columns])

    # Menangani data yang kosong
    df_clean = df_clean.dropna()

    # Menangani data duplikasi
    df_clean.drop_duplicates(inplace=True)

    # Save Hasil
    output_dir = '/content/drive/MyDrive/Tugas Pijak/SMSL_M. Haidar/preprocessing'
    os.makedirs(output_dir, exist_ok=True)

    output_file = f'{output_dir}/house_prices_clean.csv'
    df_clean.to_csv(output_file, index=False)

    print(f"Berhasil! Data bersih disimpan di: {output_file}")
    print(f"Baris akhir: {df_clean.shape[0]}")

if __name__ == "__main__":
    df = load_data()
    if df is not None:
        run_preprocessing(df)

